Walkthrough 3 - low dode development
integr8ly/tutorial-web-app-walkthroughs pull request #92
Opened 2019-08-19 16:31 UTC by finp

2019-08-20 14:26 UTC, damienomurchu commented
@fin

2019-08-21 10:57 UTC, finp commented
@aidenkeating  do we need to update the walkthrough.json in this PR?

2019-08-21 12:02 UTC, aidenkeating commented
@finp No we shouldn't need to, the `.templates` config is optional. Happy to test this out on OpenShift 4 if needed though?

2019-08-22 13:40 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Create*.
```suggestion
. Click *Save*.
```

2019-08-22 13:41 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. When prompted choose *Create from scratch* and click *Next* to navigate to the *API Designer*.
```suggestion
. When prompted choose *Create* and click *Next* to navigate to the *API Designer*.
```

2019-08-22 13:49 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +
```suggestion
. Click *Create flow* for the /greeting POST operation you just created
```

2019-08-22 13:50 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Next* on the *New Integration* wizard screen.
```suggestion
. Click *Publish* on the *New Integration* wizard screen.
```

2019-08-22 13:51 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Save and Continue* to save your API design.
```
. Click *Save and publish* to save your API design.
```

2019-08-22 13:54 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click the *Edit flow* button. The *Add to Integration* page appears displaying the *Provided API* and the *Provided API Return Path*.
```suggestion
. Click the *Create flow* button. The *Add to Integration* page appears displaying the *Provided API* and the *Provided API Return Path*.
```

2019-08-22 13:55 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Use the *Channel* dropdown to select the *low-code-demo* channel and click *Done*.
```suggestion
. Use the *Channel* dropdown to select the *low-code-demo* channel and click *Next*.
```

2019-08-22 14:14 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +.. From the *Overview* screen, select the *Configure APIcast* button.
```suggestion
.. From the *Overview* screen, select the *edit APIcast configuration* link.
```

2019-08-22 14:23 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +=== Invoking the API
This section seems to duplicate the previous one:

![Screenshot from 2019-08-22 15-22-57](https://user-images.githubusercontent.com/12085451/63522725-d36f6980-c4f0-11e9-814e-3d4f0645c3d8.png)

2019-08-22 14:24 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +curl -d '{"name":"John"}' -H "Content-Type: application/json" -X POST "{route}/greeting?user_key=test"
`{route}` renders as {route} in walkthrough, and isn't replaced by actual route

2019-08-22 14:27 UTC, damienomurchu commented
@finp Finished verifying walkthrough in a cluster provisioned with 1.5.0-RC2. Was able to complete walthrough, but there have been some small changes in the UI's of Fuse & 3scale and have left some suggested corrections. Also some slight duplication in last step which I flagged in a comment too.

2019-08-23 11:55 UTC, briandooley requested changes
Unable to get past fuse app section.

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +This walkthrough demonstrates how to implement a container-native OpenAPI RESTful API without coding.
Formatting looks a bit iffy.  See https://www.dropbox.com/s/s6jfzqduojpk1mq/Screenshot%202019-08-23%20at%2011.46.27.png?dl=0

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +A standard, programming language-agnostic interface description for REST APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access
Is this sentence too long?

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +
If you have 2FA enabled on your slack account, you will have to enter the 2FA code after clicking *Next*.  It won't go straight to "What's the name of your company or team?"

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. When prompted *What's the name of your company or team'* enter::
```suggestion
. When prompted *What's the name of your company or team?* enter::
```

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +
```suggestion
. Click *See Your Channel in Slack*
```

2019-08-23 11:55 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.
{fuse-url} points to https://eval.apps.city.openshiftworkshop.com/ , which is a dead link.  Unable to proceed further.

2019-08-23 16:15 UTC, briandooley requested changes
Unable to complete walkthrough due to issue detailed in https://issues.jboss.org/browse/INTLY-3021

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +.. Login using the email address associated with your workspace.
You should be already logged into slack at this stage.

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +.. Login using the email address associated with your workspace.
Logged in already.

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +.. Click *Create token* button next to a workspace you own, or have admin rights for.
```suggestion
.. Click *Create token* button next to *low-code-workspace*.
```

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +
```suggestion

. Choose *Integrations* from the left navigation menu.

```

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click your new */greeting* endpoint under the *Paths* heading.
No need for this instruction, already clicked.

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +    "name": "shadowman"
```suggestion
"name": "shadowman" 
```

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. In the *Request Body* section, choose the *Name* type that you created earlier.
Needs more details.  It is not possible to choose the *Name* data type as "No request body has been defined.".  Type should be "string as string".

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Publish* on the *New Integration* wizard screen.
There is no "publish" button.  Clicking "Next" brings you to a screen with a "Publish" button.

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Save* to save your API design.
```suggestion
. Click *Save and Publish* to save your API design.
```

2019-08-23 16:15 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Publish* to trigger an link:https://docs.openshift.com/container-platform/3.11/creating_images/s2i.html[Source to Image (S2I), window="_blank"] build.
```suggestion
. Click *Publish*, and then *Save and Publish", to trigger an link:https://docs.openshift.com/container-platform/3.11/creating_images/s2i.html[Source to Image (S2I), window="_blank"] build.
```

2019-08-27 09:15 UTC, damienomurchu commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +    "name": "shadowman"
I would leave this as-is; indentation is expected in the json object.

2019-08-27 09:53 UTC, finp commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +This walkthrough demonstrates how to implement a container-native OpenAPI RESTful API without coding.
create a jira

2019-08-27 09:54 UTC, finp commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +A standard, programming language-agnostic interface description for REST APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access
make suggestion

2019-08-27 10:02 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +A standard, programming language-agnostic interface description for REST APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access
A standard, programming language-agnostic interface description for REST APIs. It allows both humans and computers to discover and understand the capabilities of a service without requiring access to source code, additional documentation, or inspection of network traffic.

2019-08-27 14:24 UTC, briandooley commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +This walkthrough demonstrates how to implement a container-native OpenAPI RESTful API without coding.
Done.  https://issues.jboss.org/browse/INTLY-3067

2019-08-28 15:32 UTC, finp commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. In the *Request Body* section, choose the *Name* type that you created earlier.
out of date

2019-08-28 15:33 UTC, finp commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Save* to save your API design.
done

2019-08-28 15:33 UTC, finp commented on walkthroughs/3a-low-code-api-development/walkthrough.adoc
> +. Click *Publish* to trigger an link:https://docs.openshift.com/container-platform/3.11/creating_images/s2i.html[Source to Image (S2I), window="_blank"] build.
done

2019-08-28 16:07 UTC, merged